def get_mosei_config():
    mosei_config = {'audio_only': False,
        'audio_patch_size': [16, 16],
        'audio_size': 1024,
        'batch_size': 32,
        # 'batch_size': 8,
        'data_root': './dataset/cmumosei/',
        'datasets': ['mosei'],
        'decay_power': 1,
        'decoder_hidden_size': 512,
        'draw_false_audio': 0,
        'draw_false_text': 0,
        'draw_false_video': 0,
        'drop_rate': 0.1,
        'exp_name': 'cls_mosei',
        'fast_dev_run': False,
        'frame_masking': False,
        'frequency_size': 128,
        'get_va_recall_metric': False,
        'hidden_size': 768,
        'learning_rate': 1e-05,
        'load_hub_path': '',
        'load_local_path': '',
        'log_dir': 'result',
        'loss_names': {'mae_audio': 0,
                    'mae_video': 0,
                    'mlm': 0,
                    'mosei': 1,
                    'moseiemo': 0,
                    'vam': 0,
                    'vqa': 0,
                    'vtm': 0},
        'max_audio_patches': 1020,
        'max_epoch': 10,
        'max_frames': 64,
        'max_steps': 10,
        'max_text_len': 40,
        'mlm_prob': 0.15,
        'mlp_ratio': 4,
        'model_type': 'mae_vit_base_patch16_dec512d8b',
        'num_frames': 8,
        'num_gpus': 2,
        'num_heads': 12,
        'num_layers': 12,
        'num_nodes': 1,
        # 'num_workers': 16,
        'num_workers': 0,
        'optim_type': 'adamw',
        'patch_size': 16,
        'per_gpu_batchsize': 32,
        # 'per_gpu_batchsize': 8,
        'seed': 0,
        'strict_load': False,
        'test_only': False,
        'tokenizer': 'bert-base-uncased',
        'use_audio': True,
        'use_mae': False,
        'use_text': False,
        'use_video': True,
        'val_check_interval': 0.2,
        'video_only': False,
        'video_size': 224,
        'vocab_size': 30522,
        'vqav2_label_size': 3129,
        'warmup_steps': 100,
        'weight_decay': 0.001,
        'whole_word_masking': False}

    return mosei_config


